// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CleanMonolith.Infrastructure.Entity;
using Microsoft.EntityFrameworkCore;

namespace CleanMonolith.Infrastructure.Persistence;

public partial class nEdit_DEVContext : DbContext
{
    public nEdit_DEVContext(DbContextOptions<nEdit_DEVContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tbl_RefreshToken> Tbl_RefreshTokens { get; set; }

    public virtual DbSet<Tbl_UserMaster> Tbl_UserMasters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tbl_RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Tbl_Refr__3214EC072782E18D");

            entity.HasOne(d => d.User).WithMany(p => p.Tbl_RefreshTokens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RefreshTokens_User");
        });

        modelBuilder.Entity<Tbl_UserMaster>(entity =>
        {
            entity.Property(e => e.ActiveStatus)
                .HasDefaultValue("Active")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_ActiveStatus");
            entity.Property(e => e.CreatedBy)
                .HasDefaultValue(1L)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_CreatedBy");
            entity.Property(e => e.CreatedTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_CreatedTime");
            entity.Property(e => e.DefaultPage)
                .HasDefaultValue("Home")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_DefaultPage");
            entity.Property(e => e.InvitedMail)
                .HasDefaultValue((byte)0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_InvitedMail");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_IsDeleted");
            entity.Property(e => e.IsEditable)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_IsEditable");
            entity.Property(e => e.IsRemember)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_IsRemember");
            entity.Property(e => e.IsSSO).HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_IsSSO");
            entity.Property(e => e.Password)
                .HasDefaultValue("test")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_Password");
            entity.Property(e => e.SecurityQuestionID).HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_SecurityQuestionID");
            entity.Property(e => e.UpdatedBy)
                .HasDefaultValue(1L)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_UpdatedBy");
            entity.Property(e => e.UpdatedTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_UpdatedTime");
            entity.Property(e => e.UserType)
                .HasDefaultValue("General")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Tbl_UserMaster_UserType");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}