// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CleanMonolith.Infrastructure.Entity;

[Table("Tbl_UserMaster")]
public partial class Tbl_UserMaster
{
    [Key]
    public long UserID { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoginID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoginName { get; set; }

    [StringLength(100)]
    public string FirstName { get; set; }

    [StringLength(100)]
    public string LastName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Gender { get; set; }

    public DateOnly? DOB { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ActiveStatus { get; set; }

    public int? RoleID { get; set; }

    public string RoleIdList { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string PhoneNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmailID { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Address { get; set; }

    public int? LocationID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BloodGroup { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string WorkPhone { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string WorkExtNo { get; set; }

    [Unicode(false)]
    public string Image { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string DefaultPage { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UserType { get; set; }

    public int SecurityQuestionID { get; set; }

    [StringLength(255)]
    public string QuestionAnswer { get; set; }

    public byte? InvitedMail { get; set; }

    public bool IsEditable { get; set; }

    public bool IsSSO { get; set; }

    [StringLength(100)]
    public string Themes { get; set; }

    public bool? IsRemember { get; set; }

    public long? VendorId { get; set; }

    public string DepartmentList { get; set; }

    public string ServiceList { get; set; }

    public int? LoginFailedCount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LoginFailedDate { get; set; }

    [StringLength(255)]
    public string LoginFailedRemarks { get; set; }

    public long CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedTime { get; set; }

    public long UpdatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedTime { get; set; }

    public byte IsDeleted { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Tbl_RefreshToken> Tbl_RefreshTokens { get; set; } = new List<Tbl_RefreshToken>();
}