// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CleanMonolith.Infrastructure.Entity;

public partial class Tbl_RefreshToken
{
    [Key]
    public int Id { get; set; }

    public long UserId { get; set; }

    [Required]
    [StringLength(500)]
    public string TokenHash { get; set; }

    [StringLength(100)]
    public string JwtId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiryDate { get; set; }

    public bool IsUsed { get; set; }

    public bool IsRevoked { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Tbl_RefreshTokens")]
    public virtual Tbl_UserMaster User { get; set; }
}